test(sms): Disable SmsTest due to Netsim migration
Disable SmsTest by annotating the class with @Ignore.

ModemSimulator and the incubating ModemService gRPC endpoint were
removed from hardware/generic/goldfish in commit 8e6ed565d9e
("Remove ModemSimulator and legacy ModemService", topic "netsim-modem")
as cellular emulation is migrated to Netsim.

Without the ModemService gRPC service registered on the emulator,
invocations of ModemBlockingStub.receiveSms fail with:
io.grpc.StatusRuntimeException: UNIMPLEMENTED

Change-Id: I1c764b468e20905195e0350e045cf4f766bf25d1